# Generated by Django 6.1.1 on 2026-10-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_vehicles_details',
            fields=[
                ('vehicle_no', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=5)),
                ('owner_mob_no1', models.IntegerField()),
                ('owner_mob_no2', models.IntegerField()),
                ('license_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fees_paid', models.CharField(max_length=10)),
            ],
        ),
    ]
